/* tslint:disable */
/* eslint-disable */
/**
 * Pet Store Service
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Toy
 */
export interface Toy {
    /**
     * 
     * @type {number}
     * @memberof Toy
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof Toy
     */
    petId: number;
    /**
     * 
     * @type {string}
     * @memberof Toy
     */
    name: string;
}

/**
 * Check if a given object implements the Toy interface.
 */
export function instanceOfToy(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "petId" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function ToyFromJSON(json: any): Toy {
    return ToyFromJSONTyped(json, false);
}

export function ToyFromJSONTyped(json: any, ignoreDiscriminator: boolean): Toy {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'petId': json['petId'],
        'name': json['name'],
    };
}

export function ToyToJSON(value?: Toy | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'petId': value.petId,
        'name': value.name,
    };
}

