/* tslint:disable */
/* eslint-disable */
/**
 * Pet Store Service
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Toy } from './Toy';
import {
    ToyFromJSON,
    ToyFromJSONTyped,
    ToyToJSON,
} from './Toy';

/**
 * 
 * @export
 * @interface ToyListResults
 */
export interface ToyListResults {
    /**
     * 
     * @type {Array<Toy>}
     * @memberof ToyListResults
     */
    items: Array<Toy>;
    /**
     * 
     * @type {string}
     * @memberof ToyListResults
     */
    nextLink?: string;
}

/**
 * Check if a given object implements the ToyListResults interface.
 */
export function instanceOfToyListResults(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "items" in value;

    return isInstance;
}

export function ToyListResultsFromJSON(json: any): ToyListResults {
    return ToyListResultsFromJSONTyped(json, false);
}

export function ToyListResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToyListResults {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ToyFromJSON)),
        'nextLink': !exists(json, 'nextLink') ? undefined : json['nextLink'],
    };
}

export function ToyListResultsToJSON(value?: ToyListResults | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': ((value.items as Array<any>).map(ToyToJSON)),
        'nextLink': value.nextLink,
    };
}

