name: gen_dart_swagger_parser
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  # dart_mappable: ^4.2.1 # for dart_mappable
  dio: ^5.4.1
  freezed_annotation: ^2.4.1 # for freezed
  json_annotation: ^4.8.1
  retrofit: ^4.1.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  build_runner: ^2.4.8
  # dart_mappable_builder: ^4.2.1 # for dart_mappable
  freezed: ^2.4.7 # for freezed
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  swagger_parser:

### swagger_parser
# https://pub.dev/packages/swagger_parser
# fvm dart run swagger_parser && fvm dart run build_runner build -d
swagger_parser:
  schema_path: ../openapi.yaml
  output_directory: ./lib
  # serializers: json_serializable, freezed, dart_mappable.
  json_serializer: freezed
  unknown_enum_value: true
  merge_clients: true
  root_client_name: RestClient
