/**
 * Pet Store Service
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Pet } from '../models/Pet';
import { HttpFile } from '../http/http';

export class PetListResults {
    'items': Array<Pet>;
    'nextLink'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<Pet>",
            "format": ""
        },
        {
            "name": "nextLink",
            "baseName": "nextLink",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PetListResults.attributeTypeMap;
    }

    public constructor() {
    }
}

